### ISSUE TITLE
Error displaying the edit form for this block

### ISSUE THREAD

**Issue by digitall-it** [dnadesign/silverstripe-elemental-virtual#23]
Installing the module on Silverstripe 4.3 with Elemental 4, on adding alone on a page it shows the error message in a popup `Error displaying the edit form for this block`

**Comment by wilr** [comment]
Should be fixed on 9f4322d

**Comment by digitall-it** [comment]
There seems to be still a problem with searching the linked record. Thank you for your support!

![schermata 2019-02-28 alle 16 39 59](https://user-images.githubusercontent.com/3578378/53578363-d4de5b80-3b77-11e9-91fd-c35026bd666a.png)

**Comment by wernerkrauss** [comment]
@digitall-it can you test again from latest master? I made a fix for this, see #24
