### ISSUE TITLE
Virtual Forms Elements Don't Work

### ISSUE THREAD

**Issue by robingram** [dnadesign/silverstripe-elemental-virtual#39]
If a virtual element is added that links to an `ElementForm` from [Elemental Userforms](https://github.com/dnadesign/silverstripe-elemental-userforms) an error is generated when the form is submitted.

`Fatal error: Element $id not found for this page in /.../vendor/dnadesign/silverstripe-elemental/src/Extensions/ElementalContentControllerExtension.php on line 47`

I'm not suggesting that there is a simple solution to this, if any. Just wondering if you had any thoughts.

If there isn't a way to effectively access the form controller then I think at the least it would be good to prevent the sharing of Form elements. I couldn't find a way to extend the element to permanently turn off `availableGlobally` without completely overriding the class.

**Comment by lerni** [comment]
Disable or preventing virtual UserFormElements I handle with [removing `AvailableGlobally`-filed](https://github.com/lerni/ootstra/blob/master/app/src/Extensions/ElementUserFormsExtension.php#L17) but if that functionality would be possible, it really has a huge trouble/time-saving potential for authors. I had several requests making this possible since recreating forms and having submissions in different instances is a cumbersome user experience.

**Comment by wilr** [comment]
@robingram Have had a client request this now and fix is in the pipeline. Should have a PR asap.

**Comment by wilr** [comment]
Fixed in 467885dea8cb3867f3839aa286898b7b1dd13cd5

**Comment by rasstislav** [comment]
Hi @wilr.

This issue still exists in old version (branch 1) for elemental v4. Is it possible to backport this patch commit to version 1?

Thanks
